#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) 
# using curl, it must return a page that contains the string Holberton School

echo -e 'UPDATING AND INSTALLING NginX. \n'
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo bash -c "echo 'Hello World!' > /var/www/html/index.html"
sudo service nginx restart
